"""
Builds the 4P Index (Plastic Pollution Policy Index) coding table for:

Decret n. 2008-1007 du 18 aout 2008 portant reglementation de la gestion des dechets biomedicaux
(Senegal).

No document was uploaded for this task; the full text was retrieved from two independent official
mirrors that both match the task-brief citation and URL:
  - denv.gouv.sn (www.denv.gouv.sn/telechargement/72/decrets-cadre-juridique/19089/... , as given in
    the task brief)
  - Journal Officiel du Senegal (jo.gouv.sn, archived via FAOLEX at
    https://faolex.fao.org/docs/pdf/sen92586.pdf), which additionally preserves the decree's
    signature block (Dakar, 18 August 2008; President Abdoulaye Wade; PM Cheikh Hadjibou Soumare).

KEY FINDING: Art. 3 (definitions) and Art. 4 (classification) of the decree explicitly name
plastics -- "recyclage" is defined by reference to "papier, plastique", and "dechets recyclables"
is defined as "les dechets plastiques tels que les flacons de serum, d'eau de javel, le materiel en
verre, les contenants sous pression". This satisfies Plastics Relevance Filter criterion (a)
directly for the instruments tied to this classification (segregation and treatment-stream
assignment), in addition to the general waste-governance nexus of criterion (c) that applies to the
decree's other instruments.

Produces:
  - senegal_decret_2008-1007_4p_index.csv
  - senegal_decret_2008-1007_4p_index.xlsx (formatted, wrapped, one sheet)
"""
import csv
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

COLUMNS = [
    "A_policy_name",
    "B_policy_url",
    "C_policy_year",
    "D_policy_objective",
    "E_policy_target",
    "F_policy_target_text",
    "G_policy_type",
    "H_policy_type_justification",
    "I_policy_integration",
    "J_policy_sectors_list",
    "K_policy_circularity",
    "L_policy_lifecycle_phases_list",
    "M_policy_budget",
    "N_policy_budget_text",
    "O_policy_score",
    "P_instrument_type",
    "Q_instrument_lifecycle_stage",
    "R_instrument_description",
    "S_instrument_in_force",
    "T_instrument_implementation",
    "U_instrument_implementation_text",
    "V_instrument_score",
    "W_comments",
]

# ---------------------------------------------------------------------------
# Section A - Policy-level fields (identical across every row)
# ---------------------------------------------------------------------------

POLICY_NAME = (
    "Décret n° 2008-1007 du 18 août 2008 portant réglementation de la gestion des déchets biomédicaux"
)
POLICY_URL = (
    "www.denv.gouv.sn/telechargement/72/decrets-cadre-juridique/19089/de... (as provided in task "
    "brief) ; full text at https://www.denv.gouv.sn/telechargement/72/decrets-cadre-juridique/19089/"
    "decret-portant-reglementation-de-la-gestion-des-dechets-biomedicaux.pdf and "
    "https://faolex.fao.org/docs/pdf/sen92586.pdf (Journal Officiel du Sénégal mirror)"
)
POLICY_YEAR = 2008
POLICY_OBJECTIVE = (
    "Regulates the classification, segregation, packaging, pre-treatment, storage, transport, "
    "treatment and final disposal of biomedical waste generated by health facilities (hospitals, "
    "clinics, laboratories), veterinary structures, industrial producers of biomedical products, and "
    "research activities, and sets accreditation/traceability obligations for all actors in the "
    "biomedical-waste chain (Rapport de présentation; Art. 1-2). Its principal objective is protecting "
    "health workers, patients, waste handlers and the public from infection, injury and toxic exposure, "
    "and the environment from contamination -- not plastics regulation as such. However, Art. 3 "
    "(definitions) and Art. 4 (classification) explicitly and directly name plastics: 'recyclage' is "
    "defined with reference to 'papier, plastique', and the decree creates a dedicated waste category, "
    "'déchets recyclables', defined as 'les déchets plastiques tels que les flacons de sérum, d'eau de "
    "javel, le matériel en verre, les contenants sous pression' -- i.e. the very common plastic "
    "packaging of healthcare consumables (serum/IV-fluid bottles, bleach/disinfectant bottles, "
    "pressurised containers). Art. 11.1 then directs that this plastic/recyclable waste stream follow "
    "the general household-waste pathway rather than incineration or burial, making this decree a "
    "genuine (if narrowly sector-bound) plastics-waste-management instrument for the healthcare sector, "
    "consistent with the task brief's framing: 'Relevant to plastics waste management but limited to "
    "healthcare.'"
)
POLICY_TARGET = 0
POLICY_TARGET_TEXT = ""
POLICY_TYPE = 0.75
POLICY_TYPE_JUSTIFICATION = (
    "A presidential decree: 'Décrète :' issued by 'Le Président de la République' (Abdoulaye Wade), "
    "countersigned by the Prime Minister (Cheikh Hadjibou Soumaré), 'Fait à Dakar, le 18 août 2008.' "
    "It is issued by the executive branch under existing legislation (citing, among others, Loi "
    "n° 2001-01 portant Code de l'Environnement and the Code de l'Hygiène) rather than being itself an "
    "Act adopted by the National Assembly -> sub-legislative regulation, coded 0.75 per Rule 6."
)
POLICY_INTEGRATION = 1
POLICY_SECTORS_LIST = (
    "health, veterinary, industry, research, waste management, environment, "
    "local government/municipalities, chemicals, transport"
)
POLICY_CIRCULARITY = 0.75
POLICY_LIFECYCLE_PHASES_LIST = "recycling, disposal, environmental leakage"
POLICY_BUDGET = 0
POLICY_BUDGET_TEXT = ""
POLICY_SCORE_FORMULA = "[auto] O = (G + I + K + M) / 4"

policy_fields = dict(
    A_policy_name=POLICY_NAME,
    B_policy_url=POLICY_URL,
    C_policy_year=POLICY_YEAR,
    D_policy_objective=POLICY_OBJECTIVE,
    E_policy_target=POLICY_TARGET,
    F_policy_target_text=POLICY_TARGET_TEXT,
    G_policy_type=POLICY_TYPE,
    H_policy_type_justification=POLICY_TYPE_JUSTIFICATION,
    I_policy_integration=POLICY_INTEGRATION,
    J_policy_sectors_list=POLICY_SECTORS_LIST,
    K_policy_circularity=POLICY_CIRCULARITY,
    L_policy_lifecycle_phases_list=POLICY_LIFECYCLE_PHASES_LIST,
    M_policy_budget=POLICY_BUDGET,
    N_policy_budget_text=POLICY_BUDGET_TEXT,
    O_policy_score=POLICY_SCORE_FORMULA,
)

# ---------------------------------------------------------------------------
# Section B - Instrument-level fields (one dict per row)
# ---------------------------------------------------------------------------

instruments = [
    dict(
        P_instrument_type=1.0,
        Q_instrument_lifecycle_stage="Waste management",
        R_instrument_description=(
            "Art. 5: 'Toute personne physique ou morale, qui produit ou détient des déchets "
            "biomédicaux, en assure elle-même l'élimination ou le recyclage ou les fait éliminer ou "
            "recycler auprès des entreprises agréées par le Ministre chargé de la santé.' A mandatory "
            "producer/holder duty to ensure elimination or recycling of biomedical waste -- including "
            "the plastic waste stream defined at Art. 4 -- either directly or via Ministry-approved "
            "companies."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.75,
        U_instrument_implementation_text=(
            "Authority: approved companies are 'agréées par le Ministre chargé de la santé' (+0.25). "
            "Monitoring: Art. 20 requires 'les producteurs et les opérateurs' (which includes the "
            "persons targeted by Art. 5) to register their waste and ensure its traceability -- a "
            "data-collection requirement directly applicable to this duty (+0.25). Unconditional: the "
            "duty applies to 'toute personne physique ou morale' with no exemption identified (+0.25). "
            "Enforcement: no explicit fine/sanction was identified that is clearly triggered by a "
            "producer's (as opposed to an accredited operator's) breach of this specific duty -- not "
            "awarded, see the accreditation-sanctions row below for the operator-side enforcement "
            "mechanism."
        ),
        W_comments=(
            "This is the general producer-responsibility duty for biomedical waste, functionally "
            "analogous to the general waste-elimination duties coded elsewhere in this series for the "
            "Code de l'Environnement, but here explicitly extending to the sector-specific 'déchets "
            "plastiques' category defined at Art. 4."
        ),
    ),
    dict(
        P_instrument_type=1.0,
        Q_instrument_lifecycle_stage="Recycling",
        R_instrument_description=(
            "Art. 6: 'Tout déchet issu des activités médicales, pharmaceutiques, vétérinaires ou de "
            "recherche, est trié au niveau du lieu même de production et mis dans le circuit spécifique "
            "dédié à cette catégorie en fonction de la classification. Des pictogrammes d'indication "
            "des catégories de déchets par type de contenant sont affichés au niveau des lieux de tri "
            "et de collecte.' A mandatory source-segregation duty into category-specific streams "
            "(including the 'déchets recyclables'/plastics stream defined at Art. 4), with mandatory "
            "pictogram signage at sorting/collection points."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.50,
        U_instrument_implementation_text=(
            "Authority: falls under the Minister chargé de la Santé's general execution responsibility "
            "for the decree (Art. 22) (+0.25). Unconditional: 'Tout déchet...est trié' applies "
            "universally with no exemption identified (+0.25). Enforcement: no specific penalty for "
            "failure to sort waste at source was identified within this article -- not awarded. "
            "Monitoring: the pictogram-signage requirement is a compliance-visibility measure rather "
            "than an inspection/audit/data-collection mechanism as such -- not awarded."
        ),
        W_comments=(
            "This source-segregation duty is the operational precondition for the plastic/recyclable "
            "waste stream created by Art. 4 to actually be captured separately rather than incinerated "
            "or buried with infectious/anatomical waste."
        ),
    ),
    dict(
        P_instrument_type=1.0,
        Q_instrument_lifecycle_stage="Waste management",
        R_instrument_description=(
            "Art. 7: mandatory packaging at the point of generation -- 'Le conditionnement est effectué "
            "dès la production, pour éviter tout risque sanitaire et environnemental' -- with "
            "category-specific colour-coded containers, whose colour, packaging type and labelling are "
            "fixed by ministerial order; multi-use containers for infectious-risk waste must be cleaned "
            "and disinfected after every use before reuse."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.50,
        U_instrument_implementation_text=(
            "Authority: colour/packaging/labelling specifications are 'fixées par arrêté du Ministère "
            "chargé de la Santé' (+0.25). Unconditional: the core packaging-at-source duty applies "
            "without exemption (+0.25). Enforcement/Monitoring: no article-specific fine or inspection "
            "mechanism was identified for packaging compliance as distinct from the general accreditation-"
            "based sanctions regime -- not awarded."
        ),
        W_comments=(
            "Packaging standards here indirectly shape how much plastic packaging (bags, containers) is "
            "consumed by the healthcare sector itself, even though the decree does not regulate that "
            "consumption directly."
        ),
    ),
    dict(
        P_instrument_type=1.0,
        Q_instrument_lifecycle_stage="Recycling",
        R_instrument_description=(
            "Art. 11(1): treatment-stream assignment by waste category -- 'les déchets assimilés aux "
            "ordures ménagères, de même que les déchets recyclables, suivent la filière des déchets "
            "ménagers'; infectious/potentially infectious waste is incinerated, buried, or sterilised/"
            "shredded (Art. 11(2)); anatomical waste is buried or incinerated (Art. 11(3)); sharps are "
            "incinerated, buried or sterilised/shredded (Art. 11(4)); pharmaceutical waste follows a "
            "Ministry-specific procedure or is returned to the pharmacy (Art. 11(5)); special/chemical "
            "waste undergoes substance-specific treatment, and radioactive waste follows the separate "
            "radiation-protection legal regime (Art. 11(6))."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.50,
        U_instrument_implementation_text=(
            "Authority: falls under the Minister chargé de la Santé's execution responsibility (Art. 22), "
            "with pharmaceutical-waste procedures specifically elaborated 'par le Ministère chargé de la "
            "santé' (Art. 11(5)) (+0.25). Unconditional: the treatment-stream table 's'établit comme "
            "suit' is a definitive, mandatory assignment with no exemption identified (+0.25). "
            "Enforcement/Monitoring: no dedicated fine or inspection mechanism specific to mis-assignment "
            "between treatment streams was identified -- not awarded."
        ),
        W_comments=(
            "The single most directly plastics-relevant operative provision in the decree: by directing "
            "'déchets recyclables' (i.e. the plastic bottles/containers defined at Art. 4) into 'la "
            "filière des déchets ménagers' rather than incineration or landfill, this instrument links "
            "healthcare plastic waste into the general municipal solid-waste/recycling system already "
            "coded elsewhere in this series (e.g. Loi n° 2023-15, Art. 85-90; Loi n° 2001-01, Art. "
            "L32-L36)."
        ),
    ),
    dict(
        P_instrument_type=1.0,
        Q_instrument_lifecycle_stage="End of life",
        R_instrument_description=(
            "Art. 12: 'L'installation et le fonctionnement d'un incinérateur doivent être conformes à la "
            "réglementation en vigueur, notamment aux prescriptions édictées dans le dossier des "
            "installations classées. La température minimale d'incinération requise est de 800° C. Les "
            "résidus de l'incinération doivent faire l'objet d'un enfouissement hygiénique.' A technology/"
            "performance standard for biomedical-waste incinerators, cross-referencing the classified-"
            "installations (ICPE) regime and setting a minimum operating temperature and mandatory "
            "hygienic burial of ash residues."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.50,
        U_instrument_implementation_text=(
            "Authority: incinerators fall under the classified-installations ('installations classées') "
            "permitting authority (Ministère chargé de l'Environnement), already coded in detail "
            "elsewhere in this series (+0.25). Unconditional: the 800°C minimum temperature and "
            "mandatory hygienic ash burial are stated categorically with no exemption identified (+0.25). "
            "Enforcement/Monitoring: no incinerator-specific fine or inspection mechanism is stated within "
            "this decree itself (as distinct from the general ICPE inspection/enforcement regime coded "
            "separately for Décret n° 2001-282, which is not explicitly cross-referenced by article "
            "number here) -- not awarded to avoid double-counting evidence coded under a different "
            "policy entry."
        ),
        W_comments=(
            "Directly relevant to plastic-containing biomedical waste (e.g. PPE, syringes, IV tubing) "
            "that is incinerated rather than recycled: sets the minimum technical standard for how that "
            "combustion must occur. Cross-reference: the ICPE permitting/enforcement apparatus this "
            "article invokes is coded in full under Décret n° 2001-282 and Loi n° 2023-15 elsewhere in "
            "this series."
        ),
    ),
    dict(
        P_instrument_type=1.0,
        Q_instrument_lifecycle_stage="Waste management",
        R_instrument_description=(
            "Art. 10: transport conditions for biomedical waste on- and off-site -- 'se fait dans des "
            "conditions telles que la protection de l'environnement et des personnes soit assurée'; a "
            "hermetic, tamper-proof container is required for external transport, with a bulk-container "
            "(GRV) or a vehicle specifically equipped and compliant with dangerous-goods transport "
            "standards where none is available; transport must occur during periods of low traffic."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.50,
        U_instrument_implementation_text=(
            "Authority: falls under the Minister chargé de la Santé's general execution responsibility "
            "(Art. 22) (+0.25). Unconditional: the container/timing requirements are stated as mandatory "
            "conditions with no exemption identified (+0.25). Enforcement/Monitoring: no transport-"
            "specific fine or inspection/tracking mechanism distinct from the general traceability duty "
            "(coded separately below) was identified -- not awarded here to avoid double counting."
        ),
        W_comments=(
            "Applies to the transport of the plastic/recyclable waste stream alongside all other "
            "biomedical-waste categories."
        ),
    ),
    dict(
        P_instrument_type=0.40,
        Q_instrument_lifecycle_stage="Waste management",
        R_instrument_description=(
            "Art. 13: 'Quel que soit le type de traitement choisi, l'activité doit faire l'objet d'une "
            "étude d'impact environnemental et social.' A mandatory environmental (and social) impact "
            "assessment requirement for any biomedical-waste treatment activity, regardless of the "
            "treatment method chosen."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.75,
        U_instrument_implementation_text=(
            "Authority: cross-references the general EIA institutional framework (Comité technique / "
            "DEEC / Ministère chargé de l'Environnement) already coded in detail elsewhere in this series "
            "(+0.25). Monitoring: the EIA process itself constitutes the appraisal/monitoring mechanism "
            "for the treatment activity (+0.25). Unconditional: 'Quel que soit le type de traitement "
            "choisi' -- explicitly universal, with no exemption identified (+0.25). Enforcement: no "
            "specific penalty for skipping the EIA is stated within this decree itself (the general "
            "Code de l'Environnement penalty for unassessed projects, coded elsewhere, is not explicitly "
            "cross-referenced here) -- not awarded."
        ),
        W_comments=(
            "Coded as a Procedural measure (0.40, 'planning requirements'), consistent with the EIA "
            "instrument's treatment throughout this coding series."
        ),
    ),
    dict(
        P_instrument_type=0.40,
        Q_instrument_lifecycle_stage="Waste management",
        R_instrument_description=(
            "Art. 14-15 and 21: every biomedical-waste operator must obtain accreditation ('agrément') "
            "from the Ministry of Health, granted after the advisory opinion of a commission whose "
            "composition and mandate are fixed by ministerial order (Art. 14-15); accreditation is "
            "withdrawn where an inspection establishes that the operator functions in conditions "
            "dangerous to public health or in breach of applicable regulations, and the administrative "
            "authority may impose a 1-to-12-month temporary suspension in urgent cases, notified by "
            "registered letter (Art. 21)."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.75,
        U_instrument_implementation_text=(
            "Authority: 'Tout opérateur de déchets biomédicaux doit obtenir l'agrément du Ministère "
            "chargé de la Santé' (Art. 14) (+0.25). Enforcement: 'L'agrément est retiré...ou...une "
            "suspension temporaire de 1 à 12 mois' (Art. 21) -- an explicit sanction (+0.25). Monitoring: "
            "withdrawal/suspension decisions are explicitly based on findings 'après inspection' (Art. 21) "
            "(+0.25). Unconditional: not awarded -- the advisory commission's composition and mission "
            "depend on a further ministerial order not yet specified within this decree's own text (Art. "
            "15), and sanctions are conditioned on inspection findings rather than automatic."
        ),
        W_comments=(
            "The accreditation-plus-sanctions regime is the decree's central enforcement backbone for "
            "every operator handling the plastic/recyclable waste stream, alongside all other biomedical-"
            "waste categories. In-force test (Rule 12): the core accreditation duty (Art. 14, 'doit "
            "obtenir') and the sanctions power (Art. 21, 'est retiré') are mandatory and self-executing, "
            "so S=1, even though the advisory commission's specific composition (Art. 15) remains an "
            "enabling power pending a further order."
        ),
    ),
    dict(
        P_instrument_type=0.40,
        Q_instrument_lifecycle_stage="Waste management",
        R_instrument_description=(
            "Art. 20: 'Les producteurs et les opérateurs sont tenus d'enregistrer leurs déchets et d'en "
            "assurer la traçabilité.' A mandatory record-keeping and traceability duty imposed on both "
            "waste producers and operators across the whole biomedical-waste chain, including the "
            "plastic/recyclable stream."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.75,
        U_instrument_implementation_text=(
            "Authority: falls under the Minister chargé de la Santé's general execution responsibility "
            "(Art. 22) (+0.25). Monitoring: this instrument is itself an explicit data-collection "
            "requirement -- 'enregistrer leurs déchets et...assurer la traçabilité' (+0.25). "
            "Unconditional: applies to 'les producteurs et les opérateurs' generally, with no exemption "
            "identified (+0.25). Enforcement: no specific penalty distinct from the general accreditation-"
            "based sanctions (coded separately above) is stated for a traceability failure as such -- not "
            "awarded here to avoid double counting."
        ),
        W_comments=(
            "A cross-cutting monitoring/data-collection instrument applicable to every waste category "
            "and every actor coded in this table."
        ),
    ),
    dict(
        P_instrument_type=1.0,
        Q_instrument_lifecycle_stage="Waste management",
        R_instrument_description=(
            "Art. 9: 'Le stockage des déchets conditionnés, avant traitement se fait dans un local aéré "
            "et sécurisé. Le local doit être facilement décontaminable, régulièrement décontaminé (une "
            "fois par semaine au moins) de capacité suffisante et accessible au ramassage. La durée de "
            "stockage ne doit pas dépasser 48 heures.' Mandatory pre-treatment storage conditions "
            "(ventilated, secure, weekly-decontaminated premises) and a maximum 48-hour storage duration."
        ),
        S_instrument_in_force=1,
        T_instrument_implementation=0.75,
        U_instrument_implementation_text=(
            "Authority: falls under the Minister chargé de la Santé's general execution responsibility "
            "(Art. 22) (+0.25). Monitoring: the mandatory weekly decontamination cadence ('régulièrement "
            "décontaminé (une fois par semaine au moins)') functions as a recurring compliance-"
            "verification requirement (+0.25). Unconditional: the 48-hour maximum storage duration and "
            "facility conditions are stated categorically with no exemption identified (+0.25). "
            "Enforcement: no storage-specific fine is stated distinct from the general accreditation-based "
            "sanctions regime -- not awarded here to avoid double counting."
        ),
        W_comments=(
            "Applies to the plastic/recyclable waste stream during the pre-treatment storage window "
            "alongside all other biomedical-waste categories."
        ),
    ),
]

# ---------------------------------------------------------------------------
# Assemble rows, computing auto-fields O and V
# ---------------------------------------------------------------------------

O_score = round(
    (policy_fields["G_policy_type"] + policy_fields["I_policy_integration"]
     + policy_fields["K_policy_circularity"] + policy_fields["M_policy_budget"]) / 4,
    3,
)
policy_fields["O_policy_score"] = f"{O_score} [auto = (G+I+K+M)/4]"

rows = []
for inst in instruments:
    row = dict(policy_fields)
    row.update(inst)
    s = row["S_instrument_in_force"]
    p = row["P_instrument_type"]
    t = row["T_instrument_implementation"]
    v = round(s * (p + t) / 2, 3)
    row["V_instrument_score"] = f"{v} [auto = S*(P+T)/2]"
    rows.append(row)

with open("4p_index/senegal_decret_2008-1007_4p_index.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=COLUMNS)
    writer.writeheader()
    for row in rows:
        writer.writerow(row)

df = pd.DataFrame(rows, columns=COLUMNS)
xlsx_path = "4p_index/senegal_decret_2008-1007_4p_index.xlsx"
df.to_excel(xlsx_path, sheet_name="4P_Index_Decret2008-1007", index=False)

wb = load_workbook(xlsx_path)
ws = wb["4P_Index_Decret2008-1007"]

header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
header_font = Font(bold=True, color="FFFFFF")
wrap_top = Alignment(wrap_text=True, vertical="top")

col_widths = {
    "A": 34, "B": 30, "C": 10, "D": 46, "E": 10, "F": 30, "G": 10, "H": 34,
    "I": 10, "J": 30, "K": 10, "L": 26, "M": 10, "N": 30, "O": 16,
    "P": 12, "Q": 16, "R": 46, "S": 10, "T": 12, "U": 40, "V": 16, "W": 40,
}
for letter in [get_column_letter(c) for c in range(1, len(COLUMNS) + 1)]:
    ws.column_dimensions[letter].width = col_widths.get(letter, 20)

for cell in ws[1]:
    cell.fill = header_fill
    cell.font = header_font
    cell.alignment = Alignment(wrap_text=True, vertical="center", horizontal="center")

for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
    for cell in row:
        cell.alignment = wrap_top

ws.freeze_panes = "A2"
ws.row_dimensions[1].height = 30
for r in range(2, ws.max_row + 1):
    ws.row_dimensions[r].height = 120

wb.save(xlsx_path)
print("Wrote", xlsx_path, "and CSV with", len(rows), "instrument rows.")
print("Policy score O =", O_score)
for row in rows:
    print(row["Q_instrument_lifecycle_stage"], "->", row["V_instrument_score"])
